# SPDX-License-Identifier: (GPL-2.0-only or LGPL-2.1-only)
# SPDX-FileCopyrightText: 2016-2024 EfficiOS Inc.

TOP_LTTNG_MODULES_DIR := $(shell dirname $(lastword $(MAKEFILE_LIST)))/../..

include $(TOP_LTTNG_MODULES_DIR)/src/Kbuild.common

ccflags-y += -I$(TOP_LTTNG_MODULES_DIR)/include

obj-$(CONFIG_LTTNG) += lttng-test.o
lttng-test-objs := probes/lttng-test.o

obj-$(CONFIG_LTTNG_CLOCK_PLUGIN_TEST) += lttng-clock-plugin-test.o
lttng-clock-plugin-test-objs := clock-plugin/lttng-clock-plugin-test.o

# vim:syntax=make
