TOP_LTTNG_MODULES_DIR := $(shell dirname $(lastword $(MAKEFILE_LIST)))/..

include $(TOP_LTTNG_MODULES_DIR)/Makefile.ABI.workarounds

ccflags-y += -I$(TOP_LTTNG_MODULES_DIR)

obj-$(CONFIG_LTTNG) += lttng-test.o
lttng-test-objs := probes/lttng-test.o

obj-$(CONFIG_LTTNG) += lttng-clock-plugin-test.o
lttng-clock-plugin-test-objs := clock-plugin/lttng-clock-plugin-test.o

# vim:syntax=make
