TOP_LTTNG_MODULES_DIR := $(shell dirname $(lastword $(MAKEFILE_LIST)))/..

include $(TOP_LTTNG_MODULES_DIR)/Makefile.ABI.workarounds

ccflags-y += -I$(TOP_LTTNG_MODULES_DIR)

obj-$(CONFIG_LTTNG) += lttng-lib-ring-buffer.o

lttng-lib-ring-buffer-objs := \
  ringbuffer/ring_buffer_backend.o \
  ringbuffer/ring_buffer_frontend.o \
  ringbuffer/ring_buffer_iterator.o \
  ringbuffer/ring_buffer_vfs.o \
  ringbuffer/ring_buffer_splice.o \
  ringbuffer/ring_buffer_mmap.o \
  prio_heap/lttng_prio_heap.o \
  ../wrapper/splice.o

# vim:syntax=make
