# SPDX-License-Identifier: (GPL-2.0-only or LGPL-2.1-only)

TOP_LTTNG_MODULES_DIR := $(shell dirname $(lastword $(MAKEFILE_LIST)))/..

include $(TOP_LTTNG_MODULES_DIR)/Kbuild.common

ccflags-y += -I$(TOP_LTTNG_MODULES_DIR)/include

obj-$(CONFIG_LTTNG) += lttng-ring-buffer-client-discard.o
obj-$(CONFIG_LTTNG) += lttng-ring-buffer-client-overwrite.o
obj-$(CONFIG_LTTNG) += lttng-ring-buffer-metadata-client.o
obj-$(CONFIG_LTTNG) += lttng-ring-buffer-client-mmap-discard.o
obj-$(CONFIG_LTTNG) += lttng-ring-buffer-client-mmap-overwrite.o
obj-$(CONFIG_LTTNG) += lttng-ring-buffer-metadata-mmap-client.o
obj-$(CONFIG_LTTNG) += lttng-ring-buffer-event-notifier-client.o
obj-$(CONFIG_LTTNG) += lttng-clock.o

obj-$(CONFIG_LTTNG) += lttng-tracer.o

obj-$(CONFIG_LTTNG) += lttng-wrapper.o

lttng-tracer-objs := lib/msgpack/msgpack.o \
                     lttng-events.o lttng-abi.o lttng-string-utils.o \
                     lttng-probes.o lttng-context.o \
                     lttng-context-pid.o lttng-context-procname.o \
                     lttng-context-prio.o lttng-context-nice.o \
                     lttng-context-vpid.o lttng-context-tid.o \
                     lttng-context-vtid.o lttng-context-ppid.o \
                     lttng-context-vppid.o lttng-context-cpu-id.o \
                     lttng-context-uid.o \
                     lttng-context-euid.o \
                     lttng-context-suid.o \
                     lttng-context-gid.o \
                     lttng-context-egid.o \
                     lttng-context-sgid.o \
                     lttng-context-vuid.o \
                     lttng-context-veuid.o \
                     lttng-context-vsuid.o \
                     lttng-context-vgid.o \
                     lttng-context-vegid.o \
                     lttng-context-vsgid.o \
                     lttng-context-interruptible.o \
                     lttng-context-need-reschedule.o \
                     lttng-context-callstack.o lttng-calibrate.o \
                     lttng-context-hostname.o \
                     probes/lttng.o \
                     lttng-tracker-id.o \
                     lttng-filter.o lttng-filter-interpreter.o \
                     lttng-filter-specialize.o \
                     lttng-filter-validator.o \
                     probes/lttng-probe-user.o \
                     lttng-tp-mempool.o \
                     lttng-event-notifier-notification.o

lttng-wrapper-objs := wrapper/page_alloc.o \
                      wrapper/random.o \
                      wrapper/trace-clock.o \
                      wrapper/kallsyms.o \
                      wrapper/irqdesc.o \
                      wrapper/fdtable.o \
                      lttng-wrapper-impl.o

ifneq ($(CONFIG_HAVE_SYSCALL_TRACEPOINTS),)
  lttng-tracer-objs += lttng-syscalls.o
endif # CONFIG_HAVE_SYSCALL_TRACEPOINTS

ifneq ($(CONFIG_PERF_EVENTS),)
  lttng-tracer-objs += lttng-context-perf-counters.o
endif # CONFIG_PERF_EVENTS

ifneq ($(CONFIG_PREEMPT_RT_FULL),)
  lttng-tracer-objs += lttng-context-migratable.o
  lttng-tracer-objs += lttng-context-preemptible.o
endif # CONFIG_PREEMPT_RT_FULL

ifneq ($(CONFIG_PREEMPT),)
  lttng-tracer-objs += lttng-context-preemptible.o
endif

lttng-tracer-objs += $(shell \
  if [ $(VERSION) -ge 4 \
    -o \( $(VERSION) -eq 3 -a $(PATCHLEVEL) -ge 15 \) ] ; then \
    echo "lttng-tracepoint.o" ; fi;)

lttng-tracer-objs += lttng-context-cgroup-ns.o

ifneq ($(CONFIG_IPC_NS),)
  lttng-tracer-objs += lttng-context-ipc-ns.o
endif

ifneq ($(wildcard $(mnt_ns_dep)),)
   lttng-tracer-objs += lttng-context-mnt-ns.o
endif

ifneq ($(CONFIG_NET_NS),)
  lttng-tracer-objs += lttng-context-net-ns.o
endif

ifneq ($(CONFIG_PID_NS),)
  lttng-tracer-objs += lttng-context-pid-ns.o
endif

ifneq ($(CONFIG_USER_NS),)
  lttng-tracer-objs += lttng-context-user-ns.o
endif

ifneq ($(CONFIG_UTS_NS),)
  lttng-tracer-objs += lttng-context-uts-ns.o
endif

ifneq ($(CONFIG_TIME_NS),)
  lttng-tracer-objs += lttng-context-time-ns.o
endif

obj-$(CONFIG_LTTNG) += lttng-statedump.o
lttng-statedump-objs := lttng-statedump-impl.o

obj-$(CONFIG_LTTNG) += probes/
obj-$(CONFIG_LTTNG) += lib/
